package packets

const (
	CKeepAliveId PacketId = iota
	CJoinGameId
	CChatMessageId
	CTimeUpdateId
	CEntityEquipmentId
	CSpawnPositionId
	CUpdateHealthId
	CRespawnId
	CSetPlayerPositionAndLookId
	CHeldItemChangeId
	CUseBedId
	CEntityAnimationId
	CSpawnPlayerId
	CCollectItemId
	CSpawnObjectId
	CSpawnMobId
	CSpawnPaintingId
	CSpawnExperienceOrbId
	CEntityVelocityId
	CDestroyEntitiesId
	CEntityId
	CEntityRelativeMoveId
	CEntityLookId
	CEntityLookAndRelativeMoveId
	CEntityTeleportId
	CEntityHeadRotationId
	CEntityStatusId
	CAttachEntityId
	CEntityMetadataId
	CEntityEffectId
	CRemoveEntityEffectId
	CSetExperienceId
	CEntityPropertiesId
	CChunkDataId
	CMultiBlockChangeId
	CBlockChangeId
	CBlockActionId
	CBlockBreakAnimationId
	CBulkMapChunksId
	CExplosionId
	CParticleOrSoundId
	CSoundId
	CParticleId
	CChangeGameStateId
	CSpawnGlobalEntityId
	COpenWindowId
	CCloseWindowId
	CSetWindowSlotId
	CSetWindowSlotsId
	CWindowPropertyId
	CConfirmTransactionId
	CUpdateSignId
	CMapId
	CUpdateBlockEntityId
	COpenSignEditorId
	CStatisticsId
	CPlayerListItemId
	CPlayAbilitiesId
	CTabCompleteId
	CScoreboardObjectiveId
	CUpdateScoreId
	CDisplayScoreboardId
	CUpdateTeamId
	CPluginMessageId
	CDisconnectId
	CServerDifficultyId
	CCombatEventId
	CCameraId
	CWorldBorderId
	CTitleId
	CSetCompressionId
	CPlayerListHeaderAndFooterId
	CLoadResourcePackId
	CUpdateEntityNbtId
)
